// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq1BviCqJBEZrS3s683gFhBYJrQMkW71w',
    appId: '1:369035094671:web:8f642bfd99c6f06dd89efa',
    messagingSenderId: '369035094671',
    projectId: 'conference-app-c1b91',
    authDomain: 'conference-app-c1b91.firebaseapp.com',
    storageBucket: 'conference-app-c1b91.appspot.com',
    measurementId: 'G-GXZ91JLHF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALUDK3xIraNGC8K055uvknxTBo9f8LbWk',
    appId: '1:369035094671:android:e30d9cefbab38f7fd89efa',
    messagingSenderId: '369035094671',
    projectId: 'conference-app-c1b91',
    storageBucket: 'conference-app-c1b91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTDguv4jBzf40L_If0W7UbCFkkpWZ3vto',
    appId: '1:369035094671:ios:be5b39f25f2eedb6d89efa',
    messagingSenderId: '369035094671',
    projectId: 'conference-app-c1b91',
    storageBucket: 'conference-app-c1b91.appspot.com',
    iosClientId: '369035094671-h92ou1lu36742pcehrn4vb815hhhgl38.apps.googleusercontent.com',
    iosBundleId: 'com.example.conference',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTDguv4jBzf40L_If0W7UbCFkkpWZ3vto',
    appId: '1:369035094671:ios:be5b39f25f2eedb6d89efa',
    messagingSenderId: '369035094671',
    projectId: 'conference-app-c1b91',
    storageBucket: 'conference-app-c1b91.appspot.com',
    iosClientId: '369035094671-h92ou1lu36742pcehrn4vb815hhhgl38.apps.googleusercontent.com',
    iosBundleId: 'com.example.conference',
  );
}
